# # # # # # # # # # # # # # #
# TCSH Grammar              #
# # # # # # # # # # # # # # #

"ls -l -a -b ; this | ls
foreach i (int, has, two)
    cat $i
end
"

###### Grammar ######
program             ::=     [ block ] EOF
                    ;

block               ::=     statement [ block ]
                    ;

statement           ::=     subshell | compound_command | control
                    ;

compound_command    ::=     [ grouping ] separator
                    ;

subshell            ::=     OPARANTH [ block ] CPARANTH
                    ;

grouping            ::=     pipeline ( ( AND_IF | OR_IF ) pipeline )*
                    ;

pipeline            ::=     command ( PIPE command )*
                    ;

command             ::=     WORD [ redirection ] [ command ]
                    ;

redirection         ::=     GREAT WORD
                    |       DGREAT WORD
                    |       LESS WORD
                    |       DLESS WORD
                    |       IO_NUMBER GREAT WORD
                    |       IO_NUMBER DGREAT WORD
                    ;

separator           ::=     NEWLINE | SEMI
                    ;

# Control Flow !
control             ::=     if_control | while_control | foreach_control | repeat_control
                    ;

if_control          ::=     IF conditional THEN NEWLINE [ block ] [ else_if_statement ] ENDIF NEWLINE
                    ;

else_if_statement   ::=     ELSE_IF conditional NEWLINE [ block ] [ else_statement ]
                    ;

else_statement      ::=     ELSE [ block ]
                    ;

conditional         ::=     OPARANTH WORD CPARANTH
                    ;

foreach_control     ::=     FOREACH NAME wordlist_expression
                    ;

wordlist_expression ::=     OPARANTH wordlist CPARANTH
                    ;

wordlist            ::=     WORD [ wordlist ]
                    ;
# ! Control Flow
