# # # # # # # # # # # # # # #
# TCSH Grammar              #
# # # # # # # # # # # # # # #

###### Grammar ######
program             ::=     [ block ] EOF
                    ;

block               ::=     statement [ block ]
                    ;

statement           ::=     grouping | control
                    ;

grouping            ::=     pipeline ( ( AND_IF | OR_IF ) pipeline )*
                    ;

pipeline            ::=     command ( PIPE command )*
                    ;

command             ::=     simple_command
                    ;

# Control Flow !
control             ::=     if_control
                    |       while_control
                    |       foreach_control
                    |       repeat_control
                    ;

if_control          ::=     IF conditional THEN [ block ] [ else_if_statement ] ENDIF
                    ;

else_if_statement   ::=     ELSE_IF conditional [ block ] [ else_statement ]
                    ;

else_statement      ::=     ELSE [ block ]
                    ;

conditional         ::=     OPARANTH expression CPARANTH
                    ;

foreach_control     ::=     FOREACH NAME wordlist_expression
                    ;

wordlist_expression ::=     OPARANTH wordlist CPARANTH
                    ;

wordlist            ::=     (WORD | NAME) [ wordlist ]
                    ;
# ! Control Flow
