image: "docker.io/epitechcontent/epitest-docker:latest"

# before_script:
#   - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
#   - ruby -v
#   - which ruby
#   - gem install bundler --no-document
#   - bundle install --jobs $(nproc)  "${FLAGS[@]}"

unit_tests:
  script:
    - make tests_run
    - ./unit_tests
    - gcovr -r .

functional_tests:
  script:
    - make
    - ./ftest.sh
