/*
** EPITECH PROJECT, 2019
** PSU_42sh_2019
** File description:
** program header file.
*/

#ifndef SH_TYPES_EXEC_RULE_H_
#define SH_TYPES_EXEC_RULE_H_

enum exec_rule_e {
    EXEC_RULE_SUCCESS,
    EXEC_RULE_ALLOCATION_FAIL,
    EXEC_RULE_AMBIGUOUS_REDIRECTION,
    EXEC_RULE_REDIRECTION_FAIL,
    EXEC_RULE_REPEAT_BADLY_FORMED_NUMBER,
    EXEC_RULE_ALIAS_LOOP,
};

#endif /* !SH_TYPES_EXEC_RULE_H_ */
