/*
** EPITECH PROJECT, 2020
** PSU_42sh_2019
** File description:
** sh prompt input
*/

#ifndef SH_PROMPT_INPUT_H_
#define SH_PROMPT_INPUT_H_

enum get_input_e
{
    GET_INPUT_CONTINUE,
    GET_INPUT_END_OF_TRANSMISSION,
    GET_INPUT_FLUSH_FAIL,
    GET_INPUT_ALLOCATION_FAIL,
    GET_INPUT_WAIT_FAIL,
    GET_INPUT_ACTION_FOUND,
    GET_INPUT_NO_VALID_ACTION,
    GET_INPUT_READ_FAIL,
};

#endif /* !SH_PROMPT_INPUT_H_ */
